# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Catharina Simioni De Rosa
tagline:          'A Jekyll theme'
description:      'Exame de qualificação de doutorado - Programa de Pós-Graduação em Ciências Odontológicas.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
