# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Estudo tridimensional da célula de Agger Nasi e suas correlações com alterações/variações anatômicas e patológicas dos seios paranasais
tagline:          'A Jekyll theme'
description:      'Projeto apresentado à Faculdade de Odontologia da Universidade de São Paulo, para exame de qualificação de doutorado, pelo Programa de Pós-Graduação em Ciências Odontológicas.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
